# APPLICATION 
app_name: translator
logger: 
  log_level: DEBUG

# CONFIG CLASS
data_text:
  language_src: en
  language_tgt: fr
  data_source: "Helsinki-NLP/opus_books"

data_path:
  weight: weight
  data_source: input
  output: output
  token: token

model:
  training:
    lr: 0.0001
    epochs: 40
    batch_size: 16
    dropout: 0.1
    load_prev_weight: True

  d_model: 128
  n_head: 4
  dd_df: 512
  
  n_encoder_layer: 2
  n_decoder_layer: 2
  seq_len: 120

  save_model_name: en_to_fr.pt


  