# APPLICATION 
app_name: translator
logger: 
  log_level: DEBUG

# CONFIG CLASS
data_text:
  language_src: en
  language_tgt: fr
  data_source: "Helsinki-NLP/opus_books"

data_path:
  weight: weight
  data_source: input
  output: output
  token: token

model:
  training:
    lr: 0.0001
    epochs: 20
    batch_size: 8

  d_model: 64
  n_head: 8
  dd_df: 2048
  
  n_encoder_layer: 2
  n_decoder_layer: 2
  seq_len: 352


  